[build]
  command = "npm ci && npm run build-storybook"
  publish = "storybook-static"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

# Configuración para Storybook
[build.processing]
  skip_processing = false

# Headers para archivos estáticos
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración para archivos CSS
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

# Configuración para archivos JS
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

# Configuración para archivos de fuentes
[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"
    Cache-Control = "public, max-age=31536000"
